### ISSUE TITLE
Default Ordering of Products

### ISSUE THREAD

**Issue by samlerch** [220613-ECommerceApp/P3-Front-End#128]
* Order products alphabetically by default. 
* This way when you load the site the products are in a consistent order everytime.
* Currently loading the page the order of products is randomized.

**Comment by Daebaks** [comment]
Can be done in the BackEnd so easily. Just adding the line "ORDER BY +the product name alphabetically+" or some sort of sorting, in the BackEnd on every method that is fetching/re-fetching 
the products from the DB. This way they will always be ordered everywhere unless I am missing something haha!
