### ISSUE TITLE
Confirmation on adding to cart

### ISSUE THREAD

**Issue by samlerch** [220613-ECommerceApp/P3-Front-End#56]
* Some sort of confirmation or indication that a user has added an item to cart when the button is pressed.
* Currently items are added but there is no way to tell this.

**Comment by Daebaks** [comment]
Will work on it next

**Comment by Daebaks** [comment]
Added in-cart item counter for product's card. It updates on adding/removing items, and registers the count. 
NEXT: will work on adding alerts to the homepage.
Work in progress in my branch locally. Pls others don't do this one.

**Comment by Daebaks** [comment]
#123
